### PR TITLE
secondary-headers

### PR DESCRIPTION
**Pull request by jbickelhaupt**
Remove press logo from secondary page headers. It will show up on
front_page only.

### CODE REVIEW

**Comment by jbickelhaupt** [comment]
@philcable #reviewmerge?

**Comment by philcable** [comment]
@jbickelhaupt There are a couple spacing issues that caused this to fail the coding standards check. Those are easy to fix, but I do have a concern that this leaves the secondary pages without any site identity at all in the header. Are we not going to provide something else for those pages?

**Comment by jbickelhaupt** [comment]
I was going to tweak the other settings for the site and have it display page titles. My thought was to leave the header links in there as they are, followed by the name of the secondary page.

**Comment by philcable** [comment]
Ah, alright. You will need a bit more code for that - I suggest continuing that work in this branch.

**Comment by philcable** [comment]
@jeremyfelt #reviewmerge?

**Pull request merged**
