### PR TITLE
WC Cleanup

### PR DESCRIPTION
**Pull request by jbickelhaupt**
seriously. done yet? sigh…

### CODE REVIEW

**Comment by jbickelhaupt** [comment]
@philcable #reviewmerge?

**Comment by jbickelhaupt** [comment]
@philcable #reviewmerge?

**Comment by philcable** [comment]
@jbickelhaupt Looking good! I do think you'll want to get rid of line 6 in `woocommerge.php`, too - otherwise, the Product Image will show up twice (that's what I saw when I looked at this in my local environment).

**Comment by jbickelhaupt** [comment]
@philcable #reviewmerge

**Pull request merged**
